# Generated by Django 5.0.2 on 2024-03-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
